name: Workflow with inputs

on:
  workflow_dispatch:
    inputs:
      mc_version:
        description: "Minecraft version (e.g. '25w03a')"
        required: true
      dry_run:
        description: "Dry-run mode"
        type: boolean
        default: false
      distinct_id:
        description: "Automatically set by the return-dispatch action (leave blank if running manually)"
        required: false

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:

    - name: Echo distinct ID ${{ inputs.distinct_id }}
      run: echo ${{ inputs.distinct_id }}

    - name: Test dry_run input handling
      run: |
        echo "dry_run_string=${{ inputs.dry_run == 'true' && 'true' || 'false' }}" >> $GITHUB_STEP_SUMMARY
        echo "dry_run_bool=${{ inputs.dry_run && 'true' || 'false' }}" >> $GITHUB_STEP_SUMMARY
