name: Queued Update

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Value to append to updates.txt"
        required: true
      distinct_id:
        description: "Automatically set by the dispatch-and-wait action (leave blank if running manually)"
        required: false

permissions:
  actions: read
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Echo distinct ID ${{ inputs.distinct_id }}
        run: echo ${{ inputs.distinct_id }}

      - name: Wait for older queued updates
        uses: Wurst-Imperium/wait-for-older-runs@master

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Commit update
        run: |
          echo "${{ github.run_number }}: ${{ inputs.value }}" >> updates.txt
          git config --local user.email "bot@example.com"
          git config --local user.name "Queue Test Bot"
          git add updates.txt
          git commit -m "Add update ${{ inputs.value }}"
          git push
